FROM nginx:latest

COPY ./src/index.html usr/share/nginx/html/index.html
COPY ./src/about-me.html usr/share/nginx/html
COPY ./src/projects.html usr/share/nginx/html
COPY ./src/skills.html usr/share/nginx/html
COPY ./src/style.css usr/share/nginx/html
COPY ./src/images/ usr/share/nginx/html